name: Mission Control CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      # This disables Create-React-Apps watch mode for running the tests
      CI: true
      # This gives a database url to the Supercharge action to run our tests against
      MONGO_URL: mongodb://localhost/nasa
    # This runs 2 build jobs against 2 different Node versions - we are testing different environments
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ["4.4"]
    runs-on: ubuntu-latest
    steps:
      # Actions are some pre-built steps provided by GitHub and the community
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Action to provide us with a MongDB to run the integration tests against
      - name: Use MongoDB from GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
